#!/bin/sh
# postinst script for sparrow
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

package_type=deb


case "$1" in
    configure)
        # Install desktop menu
        xdg-desktop-menu install /opt/sparrow/lib/sparrow-Sparrow.desktop

        # Install mime info
        xdg-mime install /opt/sparrow/lib/sparrow-Sparrow-MimeInfo.xml

        # Install the udev rules
        install -m 644 /opt/sparrow/lib/runtime/conf/udev/*.rules /etc/udev/rules.d

        # Reload the udev rules
        udevadm control --reload

        # Optionally trigger udev rules for currently connected devices
        udevadm trigger

        # Make sure the plugdev group exists
        groupadd -f plugdev

        # Make sure the current user is added to plugdev
        usermod -aG plugdev `whoami`

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
